name: SSPanel_Auto_Checkin

on:
    workflow_dispatch:
    push:
        branches:
            - master
    schedule:
        - cron: '1 */12 * * *'
    watch:
        types: 
            - started

env:
    TZ: Asia/Shanghai
    USERS: ${{secrets.USERS}}
    PUSH_KEY: ${{secrets.PUSH_KEY}}
    PUSH_TURBO_KEY: ${{secrets.PUSH_TURBO_KEY}}
    QMSG_KEY: ${{secrets.QMSG_KEY}}
    DDBOT_TOKEN: ${{secrets.DDBOT_TOKEN}} 
    TELEGRAMBOT_TOKEN: ${{secrets.TELEGRAMBOT_TOKEN}} 
    TELEGRAMBOT_CHATID: ${{secrets.TELEGRAMBOT_CHATID}}
    PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
    WEWORK_ID: ${{secrets.WEWORK_ID}}
    WEWORK_AGENT_ID: ${{secrets.WEWORK_AGENT_ID}}
    WEWORK_SECRET: ${{secrets.WEWORK_SECRET}}
    DISPLAY_CONTEXT: ${{secrets.DISPLAY_CONTEXT}}
    ALIVE: ${{secrets.ALIVE}}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            
            - name: Update to step 2
              uses: skills/action-update-step@v3
              with:
                token: ${{ secrets.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 }}
                from_step: 1
                to_step: 2
                branch_name: my-first-branch
            
            - name: Install depends
              run: |
                sudo apt-get update
                sudo apt-get -y install curl jq

            - name: Request API
              run: |
                bash ssp-autocheckin.sh
